apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - configmap.yaml
  - secrets.yaml
  - pvc.yaml
  - postgres.yaml
  - redis.yaml
  - elasticsearch.yaml
  - kafka.yaml
  - rails-app.yaml
  - ingress.yaml

commonLabels:
  app.kubernetes.io/name: test-rails-71-app
  app.kubernetes.io/version: "1.0"
  app.kubernetes.io/managed-by: kustomize

namespace: rails-app
